### ISSUE TITLE
DynamoDB Unrecognized Client Exception

### ISSUE THREAD

**Issue by jonnieb754** [alexa/skill-sample-java-smarthome-switch#1]
After going through the instructions multiple times I am getting this error also with "invalid security token".  This happens when I try to build the jar file for lambda with maven.

**Comment by mikemaas-amazon** [comment]
At which step is it failing for you? Also, can you post a reasonable section of the logs during the failure?

**Comment by jonnieb754** [comment]
Thanks so much for reaching out.  It fails on step 7 - deploy the sample
code.  When I run mvn install to package the code it fails to build based
on these errors:

com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The
security token included in the request is invalid. (Service:
AmazonDynamoDBv2; Status Code: 400; Error Code:
UnrecognizedClientException; Request ID:
MFDSUJUS7BGSTVBHQ6PG70BT3RVV4KQNSO5AEMVJF66Q9ASUAAJG)

and..

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.374 sec
<<< FAILURE!
TestPowerControllerOff(AlexaHandlerTest)  Time elapsed: 2.304 sec  <<<
ERROR!
org.json.JSONException: A JSONObject text must begin with '{' at 0
[character 1 line 1]


Just let me know if you need any more info.  Thanks.

-Jon Blout

**Comment by jonnieb754** [comment]
To me it seems like during the tests the code is only testing for namespace
and name, however, when we create the handler and response for testing
powercontroller it has a sendDeviceState method that requires a valid
security token linked from the skill.  I am wondering if this is whats
causing the errors because I don't see how the sample message from the URI
could possibly supply this value.  Wouldn't the required token need to be
generated by the alexa skill itself and be specific to the user? Thanks.

**Comment by mikemaas-amazon** [comment]
The tests only really check the Handler and Response, which is fine. They are just unit tests to catch if anything changes that might break things. For this sample, the sendDeviceState method should not need auth credentials to access user information. The sendDeviceState method writes the state to the DynamoDb table "SampleSmartHome" using the endpoint ID as the primary key. 

If I had to guess, I would have another look at your permissions to access the SampleSmartHome table in DynamoDB. The error looks like a 403. Also, if the tests fail but the .jar is built, you can proceed with the instructions. Look for the file /skill-sample-java-smarthome-switch/target/skill-sample-java-smarthome-switch-1.0.jar after mvn install.

Also, just for sanity, you can doublecheck that your prerequisites are in order from this documentation: https://docs.aws.amazon.com/lambda/latest/dg/java-create-jar-pkg-maven-no-ide.html

**Comment by jonnieb754** [comment]
The test error does not allow the .jar to be built.  I have Maven 3.5.0
installed and in fact I've gone through the 'get sample resources' section
of the instructions several times making sure I had all of the
prerequisites.  I don't think it's the problem because if I omit the
sendDevice method and put a generic alexa response in its place the code
will build successfully.  However, it then obviously won't work when
testing in the Alexa console - the request never comes through and
obviously this won't work because my state values will never be saved to
DynamoDB.

Do I, by chance, need to create a table manually in DynamoDB or is it done
for me through the code?  When I go to DynamoDB I have no existing tables.

As far as permissions, I have the policy to updateItem in DyanamoDB
included in the JSON for the policy for the lambda function which is
assigned to the lamda role just like stated in the instructions. It is as
follows: {

    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "dynamodb:UpdateItem",
                "logs:CreateLogGroup",
                "logs:PutLogEvents"
            ],
            "Resource": "*"
        }
    ]
}

I have been working on this for many weeks now trying to figure this
out with no success.  Thanks for your help.

**Comment by mikemaas-amazon** [comment]
If you don't have a `SampleSmartHome` table in DynamoDB, you will need one for running the code. 

You spotted it: the flow from the AlexaHandlerTest.GetResponse() > AlexaHandler.handler() > AlexaHandler() > sendDeviceState() expects a SampleSmartHome table.

There should have been instructions for creating that manually in the instructions - which I don't see. We have another example that creates a lot of resources for you in code up-front, but not this sample. The state table is shared across all the Switch samples so it is weird that all the instructions are missing it. I will update the sample code with a fix to the documentation. Thank you for spotting this.

In the meantime, you should be able to manually create the table called `SampleSmartHome` to get unblocked.

**Comment by jonnieb754** [comment]
Ok thanks a lot, and glad I could help.

I manually created the table and it failed with the same error. So, I
created a new IAM user and attached the skill-sample-smarthome-switch
policy directly to it.  Then I generated an access key ID and secret access
key and copied them to the .aws/credentials file.  Now it is working
perfectly.

Therefore, I believe you may need to add this step as well in the
instructions.  For some reason following the instructions automatically put
the amazon client ID and Client Secret in the .aws/credentials file instead
of the access key.  I could be missing something but for whatever reason
generating the access key for a IAM user which I called
"SampleSmartHomeUser" and then updating the credentials file made
everything work.

**Comment by mikemaas-amazon** [comment]
Resolved by commit #2.
